
name = "Holy Surf"
packages = [ ]

[files]
"animation_class.py" = "./animation_class.py"
"APItest.py" = "./APItest.py"
"armor_stand_class.py" = "./armor_stand_class.py"
"armor_stand_geo_class.py" = "./armor_stand_geo_class.py"
"big_render_controller.py" = "./big_render_controller.py"
"LICENSE" = "./LICENSE"
"lookups.zip" = "./lookups.zip"
"manifest.py" = "./manifest.py"
"merge_terrain_texture.py" = "./merge_terrain_texture.py"
"pack_icon.ico" = "./pack_icon.ico"
"python_modules.zip" = "./python_modules.zip"
"render_controller_class.py" = "./render_controller_class.py"
"speed_test.html" = "./speed_test.html"
"speed_test.py" = "./speed_test.py"
"structura_core.py" = "./structura_core.py"
"structure_reader.py" = "./structure_reader.py"
"test_structures.zip" = "./test_structures.zip"
"upTest.py" = "./upTest.py"
"Vanilla_Resource_Pack.zip" = "./Vanilla_Resource_Pack.zip"
