
name = "Holy Surf"
packages = [ ]

[files]
"animation_class.py" = "./animation_class.py"
"APItest.py" = "./APItest.py"
"armor_stand_class.py" = "./armor_stand_class.py"
"armor_stand_geo_class.py" = "./armor_stand_geo_class.py"
"big_render_controller.py" = "./big_render_controller.py"
"LICENSE" = "./LICENSE"
"manifest.py" = "./manifest.py"
"merge_terrain_texture.py" = "./merge_terrain_texture.py"
"pack_icon.ico" = "./pack_icon.ico"
"render_controller_class.py" = "./render_controller_class.py"
"speed_test.py" = "./speed_test.py"
"structura_core.py" = "./structura_core.py"
"structure_reader.py" = "./structure_reader.py"
"upTest.py" = "./upTest.py"
"libZip/lookups.zip" = "./libZip/lookups.zip"
"libZip/test_structures.zip" = "./libZip/test_structures.zip"
"libZip/Vanilla_Resource_Pack.zip" = "./libZip/Vanilla_Resource_Pack.zip"
"libZip/python_modules.zip" = "./libZip/python_modules.zip"
